# Usa una imagen oficial de Node.js.
# La etiqueta "24" selecciona una versión estable de Node.js 24.
FROM mcr.microsoft.com/devcontainers/javascript-node:24

# El comando 'postCreateCommand' en devcontainer.json se encargará de
# ejecutar 'npm install' después de que el contenedor se haya creado.
